# cmake/DeployLinux.cmake
#
# Collects all non-system shared library dependencies of BINARY into
# DEPLOY_DIR using ldd, then generates a launcher script that sets
# LD_LIBRARY_PATH before exec-ing the binary.
#
# Called via:
#   cmake -DBINARY=<path> -DDEPLOY_DIR=<path> -P cmake/DeployLinux.cmake

cmake_minimum_required(VERSION 3.18)

# ── Exclusion list ─────────────────────────────────────────────────────────
# These libraries are part of the Linux ABI and are guaranteed to be present
# on any modern Linux host — do not bundle them.
set(SYSTEM_LIB_PATTERNS
    "linux-vdso"
    "ld-linux"
    "libc\\.so"
    "libm\\.so"
    "libdl\\.so"
    "libpthread\\.so"
    "librt\\.so"
)

# Path prefixes considered "system" paths.  Used only for the conditional
# libs below — NOT applied globally, because on apt-based hosts app libs
# such as gRPC and protobuf also live under /lib/x86_64-linux-gnu/.
set(SYSTEM_PATH_PREFIXES
    "/lib/"
    "/lib64/"
    "/usr/lib/"
    "/usr/lib64/"
)

# These libs are excluded only when they resolve from a system path prefix.
# When they resolve from a custom GCC installation (e.g. /data/local/lib64/)
# they must be bundled so the binary runs on hosts with older GCC runtimes.
set(CONDITIONAL_SYSTEM_LIB_PATTERNS
    "libstdc\\+\\+\\.so"
    "libgcc_s\\.so"
)

# ── Output directories ─────────────────────────────────────────────────────
file(MAKE_DIRECTORY ${DEPLOY_DIR}/bin)
file(MAKE_DIRECTORY ${DEPLOY_DIR}/lib)

# ── Copy the binary ────────────────────────────────────────────────────────
get_filename_component(_bin_name ${BINARY} NAME)
file(COPY ${BINARY}
    DESTINATION ${DEPLOY_DIR}/bin
    FILE_PERMISSIONS
        OWNER_READ OWNER_WRITE OWNER_EXECUTE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE
)

# ── Run ldd ────────────────────────────────────────────────────────────────
execute_process(
    COMMAND ldd ${BINARY}
    OUTPUT_VARIABLE _ldd_out
    ERROR_VARIABLE  _ldd_err
    RESULT_VARIABLE _ldd_rc
)
if(NOT _ldd_rc EQUAL 0)
    message(FATAL_ERROR "ldd failed on ${BINARY}:\n${_ldd_err}")
endif()

# ── Parse and copy dependencies ────────────────────────────────────────────
# ldd output lines look like:
#   libfoo.so.1 => /path/to/libfoo.so.1 (0x...)
#   /lib64/ld-linux-x86-64.so.2 (0x...)   ← no "=>" — skip
string(REPLACE "\n" ";" _lines "${_ldd_out}")
foreach(_line IN LISTS _lines)
    if(NOT _line MATCHES "=>[ \t]+(/[^ \t(]+)")
        continue()
    endif()
    set(_lib_path "${CMAKE_MATCH_1}")

    # Skip always-system libs by name (libc, libm, etc.)
    set(_skip FALSE)
    foreach(_pat IN LISTS SYSTEM_LIB_PATTERNS)
        if(_lib_path MATCHES "${_pat}")
            set(_skip TRUE)
            break()
        endif()
    endforeach()

    # libstdc++ and libgcc_s: skip only when resolved from a system path;
    # bundle when from a custom GCC installation (e.g. /data/local/lib64/).
    if(NOT _skip)
        foreach(_pat IN LISTS CONDITIONAL_SYSTEM_LIB_PATTERNS)
            if(_lib_path MATCHES "${_pat}")
                foreach(_prefix IN LISTS SYSTEM_PATH_PREFIXES)
                    if(_lib_path MATCHES "^${_prefix}")
                        set(_skip TRUE)
                        break()
                    endif()
                endforeach()
                break()
            endif()
        endforeach()
    endif()

    if(_skip OR NOT EXISTS "${_lib_path}")
        continue()
    endif()

    get_filename_component(_lib_name "${_lib_path}" NAME)
    message(STATUS "  bundle: ${_lib_name}  (${_lib_path})")
    file(COPY "${_lib_path}" DESTINATION "${DEPLOY_DIR}/lib"
         FOLLOW_SYMLINK_CHAIN)
endforeach()

# ── Generate launcher script ───────────────────────────────────────────────
set(_launcher "${DEPLOY_DIR}/${_bin_name}.sh")
file(WRITE "${_launcher}" "\
#!/bin/sh
# Auto-generated by cmake/DeployLinux.cmake — do not edit manually.
SCRIPT_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"
export LD_LIBRARY_PATH=\"\${SCRIPT_DIR}/lib:\${LD_LIBRARY_PATH}\"
exec \"\${SCRIPT_DIR}/bin/${_bin_name}\" \"$@\"
")
file(
    COPY        "${_launcher}"
    DESTINATION "${DEPLOY_DIR}"
    FILE_PERMISSIONS
        OWNER_READ OWNER_WRITE OWNER_EXECUTE
        GROUP_READ GROUP_EXECUTE
        WORLD_READ WORLD_EXECUTE
)

message(STATUS "Deploy complete → ${DEPLOY_DIR}")
